//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emisor
    {
        public int IdEmisor { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FechaInicioOperacion { get; set; }
        public Nullable<decimal> Capital { get; set; }
    }
}
